name: github pages

on:
  workflow_run:
    workflows: [ci]
    branches: [master]
    types:
      - completed

jobs:
  gh_deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]

    # 呼び元のworkflowの結果がsuccessであればmain jobを実行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Setup node env 🏗
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      # ここでyarnを有効化しておかないと後続のcash処理がエラーになる
      - name: corepack enable
        run: corepack enable

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache node_modules 📦
        uses: actions/cache@v6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: generate 👷
        run: yarn generate

      - name: deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
